
  CREATE TABLE "OPENBIZVIEW"."GBORA08" 
   (	"CODGRA" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"CODSEC" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"CODPOZ" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"DESPOZ" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CODTIP" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(30 BYTE), 
	"FECACT" DATE, 
	 CONSTRAINT "GBORA08_PK" PRIMARY KEY ("CODGRA", "CODSEC", "CODPOZ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "GBORA08_FK1" FOREIGN KEY ("CODGRA", "CODSEC")
	  REFERENCES "OPENBIZVIEW"."GBORA02" ("CODGRA", "CODSEC") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA08"."CODGRA" IS 'CODIGO DE LA GRANJA';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA08"."CODSEC" IS 'CODIGO DLE SECTOR';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA08"."CODPOZ" IS 'CODIGO DEL POZO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA08"."DESPOZ" IS 'DESCRIPCION DEL POZO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA08"."CODTIP" IS 'CODIGO DEL TIPO DE POZO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA08"."USRCRE" IS 'USUARIO QUE CREO EL REGISTRO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA08"."FECCRE" IS 'FECHA DE CREACION DEL REGISTRO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA08"."USRACT" IS 'USUARIO QUE ACTUALIZO EL REGISTRO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA08"."FECACT" IS 'FECHA DE ACTUALIZACION DEL REGISTRO';
