
  CREATE TABLE "OPENBIZVIEW"."GBORA09" 
   (	"CODGRA" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"CODTIP" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"DESTIP" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"USRCRA" VARCHAR2(50 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(50 BYTE), 
	"FECACT" DATE, 
	 CONSTRAINT "GBORA09_PK" PRIMARY KEY ("CODGRA", "CODTIP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "GBORA09_FK1" FOREIGN KEY ("CODGRA")
	  REFERENCES "OPENBIZVIEW"."GBORA01" ("CODGRA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA09"."CODGRA" IS 'CODIGO GRANJA';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA09"."CODTIP" IS 'CODIGO DE TIPO DE POZO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA09"."DESTIP" IS 'DESCRIPCION DE TIPO DE POZO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA09"."USRCRA" IS 'USUARIO DE CREACION DEL REGISTRO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA09"."FECCRE" IS 'FECHA DE CREACION DEL REGISTRO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA09"."USRACT" IS 'USUARIO QUE ACTUALIZO EL REGISTRO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA09"."FECACT" IS 'FECHA DE ACTUALIZACION DEL REGISTRO';
