
  CREATE TABLE "OPENBIZVIEW"."GBORA07" 
   (	"CODGRA" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"FECNOT" DATE NOT NULL ENABLE, 
	"CODSEC" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"CODTAB" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"BOLETO" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"REMESA" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"COSECHADORA" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"ACARREO" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"CANA" FLOAT(126) NOT NULL ENABLE, 
	"RENDIMIENTO" FLOAT(126) NOT NULL ENABLE, 
	"TTP" FLOAT(126) NOT NULL ENABLE, 
	"FECREA" DATE NOT NULL ENABLE, 
	"PLACA" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"CHOFER" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"USRCRE" VARCHAR2(50 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(50 BYTE), 
	"FECACT" DATE, 
	 CONSTRAINT "GBORA07_PK" PRIMARY KEY ("CODGRA", "FECNOT", "CODSEC", "CODTAB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "GBORA07_FK1" FOREIGN KEY ("CODGRA", "CODSEC")
	  REFERENCES "OPENBIZVIEW"."GBORA02" ("CODGRA", "CODSEC") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."CODGRA" IS 'CODIGO GRANJA';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."FECNOT" IS 'FECHA DE NOTIFICACION';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."CODSEC" IS 'CODIGO SECTOR';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."CODTAB" IS 'CODIGO TABLON';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."BOLETO" IS 'BOLETO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."REMESA" IS 'REMESA';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."COSECHADORA" IS 'COSECHADORA';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."ACARREO" IS 'ACARREA';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."CANA" IS 'CANA';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."RENDIMIENTO" IS 'RENDIMIENTO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."TTP" IS 'tiempo transcurrido desde la quema hasta el arrime';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."FECREA" IS 'FECHA REAL DE ARRIME';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."PLACA" IS 'PLACA';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."CHOFER" IS 'NOMBRE DEL CHOFER';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."USRCRE" IS 'USUARIO QUE CREO EL REGISTRO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."FECCRE" IS 'FECHA DE CREACION DELR EGISTRO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."USRACT" IS 'USUARIO QUE ACTUALIZO EL REGISTRO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA07"."FECACT" IS 'FECHA DE ACTUALIZACION DEL REGISTRO';
