
  CREATE TABLE "OPENBIZVIEW"."GBORA01" 
   (	"CODGRA" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"DESGRA" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"NUMRIF" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"NUMTEL" VARCHAR2(11 BYTE) NOT NULL ENABLE, 
	"DIREC1" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"DIREC2" VARCHAR2(60 BYTE), 
	"PAIGRA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EDOGRA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"USRCRA" VARCHAR2(50 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(50 BYTE), 
	"FECACT" DATE, 
	 CONSTRAINT "TABLE1_PK" PRIMARY KEY ("CODGRA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA01"."CODGRA" IS 'CODIGO GRANJA';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA01"."DESGRA" IS 'DESCRIPCION GRANJA';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA01"."NUMRIF" IS 'RIF';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA01"."NUMTEL" IS 'TELEFONO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA01"."DIREC1" IS 'DIRECCION 1';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA01"."DIREC2" IS 'DIRECCION 2';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA01"."PAIGRA" IS 'PAIS DE LA GRANJA';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA01"."EDOGRA" IS 'ESTADO DE LA GRANJA';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA01"."USRCRA" IS 'USUARIO DE CREACION DEL REGISTRO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA01"."FECCRE" IS 'FECHA DE CREACION DEL REGISTRO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA01"."USRACT" IS 'USUARIO QUE ACTUALIZO EL REGISTRO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA01"."FECACT" IS 'FECHA DE ACTUALIZACION DEL REGISTRO';
