
  CREATE TABLE "OPENBIZVIEW"."GBORA06R" 
   (	"CODGRA" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"FECMUE" DATE NOT NULL ENABLE, 
	"CODSEC" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"CODTAB" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"RENDIMIENTO" FLOAT(126) NOT NULL ENABLE, 
	"USRCRE" VARCHAR2(50 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(50 BYTE), 
	"FECACT" DATE, 
	 CONSTRAINT "GBORA06R_PK" PRIMARY KEY ("CODGRA", "FECMUE", "CODSEC", "CODTAB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "GBORA06R_FK1" FOREIGN KEY ("CODGRA", "CODSEC")
	  REFERENCES "OPENBIZVIEW"."GBORA02" ("CODGRA", "CODSEC") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA06R"."CODGRA" IS 'CODIGO DE GRANJA';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA06R"."FECMUE" IS 'FECHA DE MUESTRA';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA06R"."CODSEC" IS 'CODIGO DE SECTOR';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA06R"."CODTAB" IS 'CODIGO DE TABLON';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA06R"."RENDIMIENTO" IS 'PORCENTAJE DE RENDIMIENTO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA06R"."USRCRE" IS 'USUARIO QUE CREO EL REGISTRO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA06R"."FECCRE" IS 'FECHA DE CREACION DELR EGISTRO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA06R"."USRACT" IS 'USUARIO QUE ACTUALIZO EL REGISTRO';
   COMMENT ON COLUMN "OPENBIZVIEW"."GBORA06R"."FECACT" IS 'FECHA DE ACTUALIZACION DELR EGISTRO';
